### ISSUE TITLE
Offline activation method does not work,

### ISSUE THREAD

**Issue by advur** [guiqui/k8Studio#82]
The offline activation method does not work, because the domain licenses.k8 studio.io in the instruction is not resolving.

**Comment by guiqui** [comment]
Thank you for letting us know. 
We are going to fix our DNS config.

**Comment by guiqui** [comment]
Hello Thank you again, we just fixed the DNS.
https://licenses.k8studio.io/login should be working now. You may need to flush the DNS entry or wait for the ttl.

**Comment by advur** [comment]
Thanx! It really works now. But I still can't see any button or anything where i can validate my offline activation code.

**Comment by mo-othman** [comment]
We have launched the documentations

https://doc.k8studio.io/documentation/activation-and-licenses/professional-airtight
